services:
  postgres:
    image: postgres:16
    container_name: lab2-postgres
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab -d lab"]
      interval: 5s
      timeout: 5s
      retries: 20

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: lab2-clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: lab
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --password lab --query 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 20

  spark:
    image: apache/spark:3.5.1
    container_name: lab2-spark
    user: root
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/lab
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123/default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: lab
      HOME: /tmp
      DATA_PATH: /data/*.csv
    ports:
      - "4040:4040"
    volumes:
      - ./spark_jobs:/opt/spark-apps
      - ./исходные данные:/data:ro
      - spark_events:/tmp/spark-events
    command: ["/bin/sh", "-c", "mkdir -p /tmp/spark-events && chmod 777 /tmp/spark-events && sleep infinity"]

  spark-history:
    image: apache/spark:3.5.1
    container_name: lab2-spark-history
    user: root
    depends_on:
      - spark
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_HISTORY_OPTS: "-Dspark.history.fs.logDirectory=file:/tmp/spark-events -Dspark.history.ui.port=18080"
    ports:
      - "18080:18080"
    volumes:
      - spark_events:/tmp/spark-events
    command: ["/bin/sh", "-c", "mkdir -p /tmp/spark-events && chmod 777 /tmp/spark-events && /opt/spark/sbin/start-history-server.sh"]

volumes:
  postgres_data:
  clickhouse_data:
  spark_events:
